include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

  errors:
    missing_required_param: error
    missing_return: error
    todo: warning
    deprecated_member_use: warning
    use_build_context_synchronously: error
    invalid_use_of_protected_member: warning

  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"
    - "build/**"
    - ".dart_tool/**"

linter:
  rules:
    # ==========================================
    # A. ERROR PREVENTION (PHÒNG NGỪA LỖI)
    # ==========================================
    use_build_context_synchronously: true # QUAN TRỌNG NHẤT
    avoid_dynamic_calls: true # Tránh runtime errors
    avoid_print: true # Dùng Logger
    avoid_web_libraries_in_flutter: true # Chỉ dùng web libs đúng chỗ
    cancel_subscriptions: true # Tránh memory leak
    close_sinks: true # Tránh resource leak
    unnecessary_null_checks: true # Clean code

    # ==========================================
    # B. CODE QUALITY (CHẤT LƯỢNG CODE)
    # ==========================================
    prefer_const_constructors: true # Tối ưu performance
    prefer_const_declarations: true # Immutable data
    prefer_final_locals: true # Tránh accidental mutation
    prefer_final_fields: true # Encapsulation tốt
    prefer_is_not_empty: true # Readability
    prefer_null_aware_operators: true # Null safety
    avoid_unnecessary_containers: true # Performance
    sized_box_for_whitespace: true # UI performance

    # ==========================================
    # C. STYLE & CONSISTENCY (NHẤT QUÁN)
    # ==========================================
    prefer_single_quotes: true # Dart convention
    require_trailing_commas: false # Better git diffs
    sort_child_properties_last: true # Flutter convention
    file_names: true # snake_case.dart

    # ==========================================
    # D. NAMING CONVENTIONS (QUY TẮC ĐẶT TÊN)
    # ==========================================
    camel_case_types: true # PascalCase cho class
    camel_case_extensions: true # PascalCase cho extension
    constant_identifier_names: true # UPPER_CASE cho const

    # ==========================================
    # F. PERFORMANCE RULES (HIỆU NĂNG)
    # ==========================================
    avoid_slow_async_io: true # Blocking operations
    avoid_types_as_parameter_names: true # Type safety
    no_logic_in_create_state: true # Flutter best practice

    # ==========================================
    # G. SECURITY & STABILITY (BẢO MẬT)
    # ==========================================
    do_not_use_environment: true # Hardcode sensitive data
    avoid_js_rounded_ints: true # Web-specific issue
    avoid_catches_without_on_clauses: true # Proper error handling
